import "./globals.css";
import Sidebar from "@/components/Sidebar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <div className="flex">
          <Sidebar />
          <main className="flex-grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
